### ISSUE TITLE
Radio semi-failure via MMB volume reduction

### ISSUE THREAD

**Issue by Kryxal** [Octal450/IDG-PA28#9]
### General
----

I am submitting a: (select one) 
* [x] Bug report
* [ ] Feature request

### Details
Upon pressing the MMB to reduce radio volume, the radio is apparently powered down.  Pressing LMB to increase volume does not fix this, though using scroll-wheel does.

Interestingly enough, the COMM still works but for lack of LED display, NAV sends no signal to VOR, though DME still works.

#### Expected Behavior (bug reports)
MMB expected to reduce volume without setting a power-off state.

#### Current Behavior (if applicable)
MMB causes a power-off state, same as using scroll-wheel to go to the "OFF" position

#### Steps to Reproduce (bug reports)

1. Set COMM to live frequency (such as ATIS) for reference
2. Set NAV to nearby VOR for reference
3. Turn up volume on radio by several clicks
4. Turn down volume via MMB by 1 click
5.

**Comment by Kryxal** [comment]
This issue is as of version 241, seen on FG 2019.1.1

**Comment by it0uchpods** [comment]
Will look into this shortly.

**Comment by Octal450** [comment]
Fix is on the way in the new 3d

**Comment by Octal450** [comment]
Should be fixed now. If not, please let me know and I'll re-open!
